### ISSUE TITLE
quote-posts with block relationship: show link in ozone

### ISSUE THREAD

**Issue by bnewbold** [bluesky-social/ozone#101]
When there is a block relationship between the author of a quote-post and the author of the post being quoted, the, post does not show up in ozone. This makes it hard to investigate some harassment/abuse situations.

We discussed a couple different ways we could try to bypass this behavior from Ozone, but the simplest is probably to add a link in the "post not shown" area that goes directly to the post view in ozone. There is still some friction for mods, but this doesn't require Lexicon updates, and makes it clear to mods what the situation is.

**Comment by foysalit** [comment]
#108 should have this resolved but lmk if there's anything else can be done there.
