### ISSUE TITLE
If someone's blocking the labeler account, I can't view them in Ozone unless I search by their did (and I can't see their posts)

### ISSUE THREAD

**Issue by heikadog** [bluesky-social/ozone#151]
To reproduce:

1. See someone blocked the labeler account
2. Search by handle, they don't come up
3. Search by DID, they come up but their posts don't come up

This is a problem because I don't want people to be able to block the labeler and potentially prevent moderation actions from taking place. Is this a limitation with ATProto or Ozone?

**Comment by bnewbold** [comment]
This is a bit of a combined issue between Ozone and the bsky AppView. What we probably need to do in this case is have Ozone fetch using un-authenticated public data requests, which will bypass the block.

**Comment by SteveTownsend** [comment]
I added a label to my service "Blocks Moderation" for this case, as an interim fix. Without judgment on the blocker - could be privacy, could be evasion.
Privacy makes this a thorny issue, doesn't it? I have not thought through (or read up on) why unauth public data access is not a cheat code for blocked users to see the target's posts.

**Comment by paboum** [comment]
A similar thing happens when service account is takendown, all repo queries are rejected by PDS like this:
