### ISSUE TITLE
PR140 degrades ozone container

### ISSUE THREAD

**Issue by itaru2622** [bluesky-social/ozone#157]
ozone container cannot work after #140 merged.
container raises internal server error when it got request (for login form).

the reason is next,js version mismatched between REPO_ROOT/package.json and  service/package.json

REPO_ROOT/package.json uses new next.js (14.2.5) with new parameter in next.config.js but service/package.json uses older version.

**Comment by foysalit** [comment]
yeah this has been addressed here https://github.com/bluesky-social/ozone/pull/156/files#diff-8c88f7803ea63571932bbe2feb7159a081eebde3bd735073a5fffdd107153581 as part of more 3p labeler distro related fixes.
