### ISSUE TITLE
"Load more" button shows when there's nothing to load

### ISSUE THREAD

**Issue by heikadog** [bluesky-social/ozone#195]
The "Load more" button shows in multiple places when there's nothing to load—is there a chance this could be hidden?

**Comment by mary-ext** [comment]
[This PR](https://github.com/bluesky-social/ozone/pull/201) seems to suggest it's intentional, as a way to refresh the content, I wonder if changing the label would be a lot more helpful?

**Comment by heikadog** [comment]
yeah, i feel like it should say "Refresh" instead
