### ISSUE TITLE
Feedgen text isn't visible in dark mode

### ISSUE THREAD

**Issue by rudyfraser** [bluesky-social/ozone#224]
When a feedgen is reported and you're in dark mode, the text isn't visible in the preview pane.

Dark Mode
![Screenshot 2024-10-31 at 9 09 29 AM](https://github.com/user-attachments/assets/6603c009-5bec-4659-a028-6c9d37da94e2)

Light Mode
![Screenshot 2024-10-31 at 9 11 57 AM](https://github.com/user-attachments/assets/3e7b9b80-4cf6-4344-8969-66f6c68bb80f)

**Comment by heikadog** [comment]
less important than this but there's a similar issue with #152 !

**Comment by foysalit** [comment]
I believe this has been fixed in the last release. Just checked on our instance and it seems to be working but please reopen if you find this happening again.
