### ISSUE TITLE
AssertionError [ERR_ASSERTION]: publicUrl is required (envToCfg error)

### ISSUE THREAD

**Issue by raymondandreassen** [bluesky-social/ozone#236]
Hi, first of all: Awesome work. Amazing what the team has accomplished. 

I tried to run the app in docker using
```
docker build -t ozone . --debug
docker run -p 3000:3000 ozone
```
And I get the following error:
```
AssertionError [ERR_ASSERTION]: publicUrl is required
    at envToCfg (/usr/src/ozone/node_modules/@atproto/ozone/dist/config/config.js:13:31)
    at main (/usr/src/ozone/service/index.js:21:18) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: undefined,
  expected: true,
  operator: '=='
}
``` 
I cannot find any information regarding publicUrl, but I suspect it to be an env variable. The only place I could find publicUrl been mentioned is here [verdverm: DB connection being rejected with Zalando Postgres Operator #75](https://github.com/bluesky-social/ozone/issues/75#issuecomment-2016891886)

Also, this issue resembles a lot to [docker quickstart fails to run (envToCfg error) #67](https://github.com/bluesky-social/ozone/issues/67). 

I can't see that my environment has anything to do with this issue and I cloned it today [Commit 30cb0e6
](https://github.com/bluesky-social/ozone/commit/30cb0e661452ef027425a54f7ae59129edcae766)

Any help will be appreciated.

**Comment by SteveTownsend** [comment]
Is HOSTING.md any use in diagnosing this? I used that when I set up my
moderation service, and the only things that went wrong were my own fault.
I think this refs an envvar injected to the composed container that might
be relevant.

**Comment by raymondandreassen** [comment]
HOSTING.md gave me a list of environment variable names and values ​​I need to set.
I see that I get past publicUrl, with OZONE_PUBLIC_URL set. Now it's just the rest.
Thanks!
