### ISSUE TITLE
Alternative management of labeler declaration record

### ISSUE THREAD

**Issue by bnewbold** [bluesky-social/ozone#60]
The Ozone UI for editing labeler declaration records works well for some use-cases, but not in others.

This is just a regular old atproto record, so a generic tool for editing/updating records would work, though I don't think we have such a thing in GUI/accessible form right now. Some ideas:

- ability to paste raw JSON in the text box (does this not work right now?), or an alternative text box
- ability to upload file in Ozone UI
- CLI tool to upload arbitrary JSON to a repo (on PDS). gosky (https://github.com/bluesky-social/indigo/tree/main/cmd/gosky) might even already have this?

and then documentation of a recommended path.

(this inspired by a discussion: https://github.com/bluesky-social/atproto/discussions/2335#discussioncomment-8832420)

**Comment by jonpincus** [comment]
Another usabilty improvement that would be very helpful here is to make the options with alternatives (severity / blurs / default setting) into either pulldown menus or radio buttons.  Right now, it requires some fiddly text editing when you first create the label definition; and, if you want to change it, you have to remember what the other choices are and avoid typos.  (This seemed to make more sense here but let me know if it would be better as a separate issue.)

**Comment by bnewbold** [comment]
Shipped!

**Comment by jonpincus** [comment]
Very cool, great to hear -- thanks much!
