### ISSUE TITLE
Ability to "mute" or otherwise ignore/reject reports from specific users

### ISSUE THREAD

**Issue by bnewbold** [bluesky-social/ozone#68]
There is an abuse vector for users to harass moderation services by posting bad content in reports (including appeals), possibly many times. If this happens, it would be helpful for mod teams to be able to reject or ignore new reports from that account, either for a fixed time period or indefinitely.

This is similar to the existing "mute" functionality, which applies to a "subject" (not reporter).

**Comment by monicaellerose** [comment]
this will be great when its live 🙏🏻

**Comment by bnewbold** [comment]
an implementation of this has merged. we'll do an updated "release" of ozone soon (some time next week?)

**Comment by foysalit** [comment]
This went out with the last distro release (implemented in this PR https://github.com/bluesky-social/ozone/pull/95)
