### ISSUE TITLE
Ability to edit JSON as text in /configure

### ISSUE THREAD

**Issue by baatl** [bluesky-social/ozone#80]
On top of making it easier to reorder the array of label values (which controls their ordering in the bsky.app UI), this would also permit for adding locales to the label value definitions (#36), which is not possible in the current UI.

**Comment by bnewbold** [comment]
Very similar to https://github.com/bluesky-social/ozone/issues/80, going to close as duplicate.

**Comment by baatl** [comment]
Did you just... close an issue for being similar to itself?

**Comment by bnewbold** [comment]
yes! sorry for the confusion
