### ISSUE TITLE
UI console errors with deleted post threads (reading 'handle' from undefined)

### ISSUE THREAD

**Issue by HenrickTheBull** [bluesky-social/ozone#88]
I'm getting some application errors when attempting to view the posts in a user repository. Here's the error.
![image](https://github.com/bluesky-social/ozone/assets/3945192/8f33ce5d-ed96-4c45-aa4b-2f7a57f4506d)

For safety and security if the DID of the user is required to attempt to replicate the bug I'll only relay it via email at henrick [at] thebull [dot] app.

**Comment by foysalit** [comment]
@HenrickTheBull I believe we've fixed this already via this PR https://github.com/bluesky-social/ozone/pull/96 I'd really appreciate if you could pull latest main and see if you can still repro.

**Comment by foysalit** [comment]
This was resolved but do re-open if you see it happen again/anywhere else.

**Comment by HenrickTheBull** [comment]
I'm not sure if this is related to the previous issue I reported but it seems to have some of the same properties, when trying to view a posts on a repository for moderation purposes things seem to go wrong.


![Screenshot_20240520_032146](https://github.com/bluesky-social/ozone/assets/3945192/5c5274f7-1309-47a7-8001-b54e1a094657)
![Screenshot_20240520_032250](https://github.com/bluesky-social/ozone/assets/3945192/eeffbd8f-e811-4b39-9f38-b4f9e6f47eef)
![Screenshot_20240520_032524](https://github.com/bluesky-social/ozone/assets/3945192/b8e80481-9e8c-44fa-b759-14a61e2a107b)


Also @foysalit sorry for not responding on the issue previously I had a lot on my plate at the time and didn't get the email for the reply.
